create table coins (
    coin_id varchar(255) primary key,
    symbol varchar(50) not null,
    name varchar(255) not null,
    image_url text,
    current_price decimal,
    market_cap decimal,
    market_cap_rank int,
    fully_diluted_valuation decimal,
    total_volume decimal,
    high_24h decimal,
    low_24h decimal,
    price_change_24h decimal,
    price_change_percentage_24h decimal,
    market_cap_change_24h decimal,
    market_cap_change_percentage_24h decimal,
    circulating_supply decimal,
    total_supply decimal,
    max_supply decimal,
    ath decimal,
    ath_change_percentage decimal,
    ath_date timestamptz,
    atl decimal,
    atl_change_percentage decimal,
    atl_date timestamptz,
    price_change_percentage_1h decimal,
    price_change_percentage_7d decimal,
    price_change_percentage_14d decimal,
    price_change_percentage_30d decimal,
    price_change_percentage_200d decimal,
    price_change_percentage_1y decimal,
    sparkline_7d jsonb,
    roi jsonb,
    coingecko_last_updated timestamptz,
    last_synced_at timestamptz not null default now()
);
