create table coin_detail (
    coin_id varchar(255) primary key references coins(coin_id) on delete cascade,
    description text,
    categories text[],
    hashing_algorithm varchar(100),
    block_time_in_minutes int,
    genesis_date date,
    country_origin varchar(255),
    homepage text[],
    blockchain_sites text[],
    official_forum_urls text[],
    chat_urls text[],
    announcement_urls text[],
    whitepaper text,
    twitter_username varchar(100),
    facebook_username varchar(100),
    telegram_channel_identifier varchar(100),
    subreddit_url text,
    github_repositories text[],
    bitbucket_repositories text[],
    platforms jsonb,
    detail_platforms jsonb,
    sentiment_votes_up_percentage decimal,
    sentiment_votes_down_percentage decimal,
    watchlist_portfolio_users bigint,
    developer_data jsonb,
    community_data jsonb,
    coingecko_last_updated timestamptz,
    last_synced_at timestamptz not null default now()
);
